# Generated by Django 2.1.2 on 2018-10-20 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooks',
            name='Availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mydeletedbooks',
            name='Date_Deleted',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 20, 15, 49, 54, 978244)),
        ),
    ]
