# Generated by Django 2.1.2 on 2018-10-21 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20181020_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myDeletedBooks',
        ),
        migrations.AddField(
            model_name='mybooks',
            name='Book_Art',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mybooks',
            name='Date_Added',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 21, 16, 27, 42, 650516)),
        ),
        migrations.AddField(
            model_name='mybooks',
            name='Type',
            field=models.CharField(default='Horror', max_length=250),
        ),
    ]
