# Generated by Django 2.1.2 on 2018-10-23 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0004_auto_20181021_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybooks',
            name='Availability',
        ),
        migrations.AlterField(
            model_name='mybooks',
            name='Date_Added',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 23, 15, 50, 30, 761243)),
        ),
    ]
